### ISSUE TITLE
Missing X11 workspace in Nobara 40

### ISSUE THREAD

**Issue by ANBAL534** [Nobara-Project/nobara-images#11]
In Nobara 40 the package `plasma-workspace-x11` is not installed by default, and thus not able to select X11 desktop on first login.

For a newbie its best to have this installed by default, so it can change to X11 instead of Wayland for better functionality (Ex.: screensharing in discord is not available in wayland)

In most threads regarding this kind of issues its only explained how to change in the login screen from Wayland to X11, assuming that this package is already installed in Nobara (it was in older versions).

**Comment by GloriousEggroll** [comment]
https://wiki.nobaraproject.org/graphics/nvidia/supported-gpus
`It should be additionally noted, Nobara 41 and higher do not ship with X11 packages and also does not support X11 moving forward.`
