### ISSUE TITLE
Nobara 40 won't boot in Win11 Hyper-V and VirtualBox

### ISSUE THREAD

**Issue by GordonFreeeman** [Nobara-Project/nobara-images#12]
Weird issue, I spent hours trying to get Nobara v40 to work in both Hyper-V and VirtualBox in Windows 11. It always booted into a black screen with a frozen cursor in the middle. I managed to trigger the install process by booting into safe mode (w/o graphics drivers), but after the install, I would get the same black screen issue again.

I'm using the correct VM settings (secure boot disabled), tried all fixes I could find at stackoverflow, but no luck.

I then noticed in a very basic "how to install" video on YT that the guy was using v39. So I downloaded that one via direct link (https://nobara-images.nobaraproject.org/Nobara-39-Official-2024-01-11.iso), and it worked out of the box, without any issues. I'm running it right now in fact, typing this post from within the VM.

Are you aware of this issue? Is it maybe a general Fedora bug? Or am I missing something? 😇

**Comment by Lartza** [comment]
Likely the installer is not adding nomodeset to the system's boot entry, and that is basically what the basic graphics option should do on the ISO. You can try manually adding it.

**Comment by GordonFreeeman** [comment]
Thanks, I'll try that. :-)

**Comment by GloriousEggroll** [comment]
closing, no follow up
