### ISSUE TITLE
ROCm (gfx1010)

### ISSUE THREAD

**Issue by nexsus312** [Nobara-Project/nobara-images#13]
When installing ROCm via Driver Manager, the file TensileLibrary_lazy_gfx1010.dat is missing.
I found out that it can be produced by building rocBLAS with certain parameters. But this is beyond my knowledge. Is it possible to do it by myself?
 [Tensile won't produce backend libraries for archs without optimized logic files when using --separate-architectures #1757 ](https://github.com/ROCm/Tensile/issues/1757)

**Comment by GloriousEggroll** [comment]
we do not build nor provide ROCm directly. In Nobara 40 and older they came fro AMD's ROCm repository directly (contact AMD about the issue). In Nobara 41 we have moved to Fedora upstream's ROCm packages -- unmodified. 

According to dnf TensileLibrary_lazy_gfx1010.dat should come included in the rocblas package provided by fedora:
```
rocblas-6.2.1-1.fc41.x86_64 : BLAS implementation for ROCm
Repo         : updates
Matched From : 
Filename     : /usr/lib64/rocblas/library/TensileLibrary_lazy_gfx1010.dat
Filename     : /usr/lib64/rocm/gfx10/lib/rocblas/library/TensileLibrary_lazy_gfx1010.dat

```
closing as resolved in N41
