### ISSUE TITLE
Can't install Nobara Linux

### ISSUE THREAD

**Issue by Drsheppard01** [Nobara-Project/nobara-images#8]
Can't install Nobara Linux with custom partitioning, include pre installed home on xfs.
UEFI is enabled
Load in UEFI mode
CSM module is disabled
Secure boot is disabled (other os, keys was deleted)

Manual partioning:
1. boot, 2Gb, FAT32, boot flag enabled
2. /, 100 Gb, XFS, any flag isn't set
3. /home, all left space, XFS,any flag isn't set

1. Install with that parameters
2. Reboot
3. GRUB issue (looks like he can't find boot partition)

**Comment by GloriousEggroll** [comment]
you need /boot and /boot/efi:

https://feed.nobaraproject.org/en/for-manual-partitioning?user_id=4d1a404a-d5a8-4f9b-be87-4eb37b753cd3

**Comment by s1arsky** [comment]
the real bug is Calamares accepting a partition layout it can't handle.
