### ISSUE TITLE
Debloat / Simplify Nobara

### ISSUE THREAD

**Issue by Drsheppard01** [Nobara-Project/nobara-images#9]
The large number of applications may scare off an inexperienced user, so I suggest the following:

1. Console instead Terminal (more appropriate view of app)
2. Clapper or (Showtime which uses Clapper-libs) instead Totem and Rthythmbox (Capable of replacing them both)
3. Foliate instead Evince (more formats, not only pdfs and post/ghostscripts)
4. Remove from OOB gnome-connections, gnome-weather, gnome-contacts, gnome-maps, gnome-disk-utility, baobab
5. looks like lpf needed only for building xone (software for xbox controller) and it depends by nobara-welcome but i think it's no needed for every gamers

**Comment by GloriousEggroll** [comment]
This has been discussed many times. There will be no further "debloating" of Nobara images.
